name: Publish Image Using Semver Tag (bcftools)

on:
  push:
    tags:
      - bcftools-v*

jobs:
  publish-bcftools:
    name: Publish BCFtools Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract Version Tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/bcftools-v}" >> $GITHUB_ENV
      - name: Push the image on the registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/bcftools
          location: bcftools
          dockerfile: bcftools/Dockerfile
          tag_format: "${{ env.VERSION }}"
