name: Publish Image Using latest (bcftools)

on:
  push:
    branches:
      - main

jobs:
  publish-bcftools:
    name: Publish BCFtools Image latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push the image on the registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/bcftools
          location: bcftools
          dockerfile: bcftools/Dockerfile
          tag_format: "latest"
